graph TD
    DrawBoxGTC["DrawBoxGTC<br/>Calls: 0"]
    DrawPolylineFromSeed["DrawPolylineFromSeed<br/>Calls: 0"]
    DrawPolylineFromFile1["DrawPolylineFromFile1<br/>Calls: 0"]
    DrawPolyline_Old["DrawPolyline_Old<br/>Calls: 0"]
    DrawPanel["DrawPanel<br/>Calls: 0"]
    CheckPolylineVertices["CheckPolylineVertices<br/>Calls: 0"]
    FixVertices["FixVertices<br/>Calls: 0"]
    TestWriteLines["TestWriteLines<br/>Calls: 0"]
    ReadVerticesToFile["ReadVerticesToFile<br/>Calls: 0"]
    ReadMultFromFiles["ReadMultFromFiles<br/>Calls: 0"]
    RemoveVerticesPickTwoPoints["RemoveVerticesPickTwoPoints<br/>Calls: 0"]
    JoinPloylines["JoinPloylines<br/>Calls: 0"]
    GetLineInfoFromStomp["GetLineInfoFromStomp<br/>Calls: 0"]
    DrawPanelFeeders["DrawPanelFeeders<br/>Calls: 0"]
    DrawPolylineFromFileSp["DrawPolylineFromFileSp<br/>Calls: 0"]
