graph TD
    Adds["Adds"]
    IExtensionApplication["IExtensionApplication"]
    IExtensionApplication --> Adds
    GripVectorOverrule["GripVectorOverrule"]
    GripOverrule["GripOverrule"]
    GripOverrule --> GripVectorOverrule
    Adds["Adds"]
    IExtensionApplication["IExtensionApplication"]
    IExtensionApplication --> Adds
    TextJig["TextJig"]
    DrawJig["DrawJig"]
    DrawJig --> TextJig
    MovementJig["MovementJig"]
    DrawJig["DrawJig"]
    DrawJig --> MovementJig
    RotationJig["RotationJig"]
    DrawJig["DrawJig"]
    DrawJig --> RotationJig
    TextJig["TextJig"]
    EntityJig["EntityJig"]
    EntityJig --> TextJig
    PlineJig["PlineJig"]
    EntityJig["EntityJig"]
    EntityJig --> PlineJig
    BlockJig["BlockJig"]
    EntityJig["EntityJig"]
    EntityJig --> BlockJig
    BlockJig2["BlockJig2"]
    EntityJig["EntityJig"]
    EntityJig --> BlockJig2
